passing cfn validation

diff --git a/template/backendless_chef.yml b/template/backendless_chef.yml
--- a/template/backendless_chef.yml
+++ b/template/backendless_chef.yml
@@ -447,7 +447,7 @@ Resources:
   RolePolicies:
     Type: AWS::IAM::Policy
     Properties:
-      - PolicyName: !Sub ${ChefSubdomain}-S3Role-${AWS::Region}
+        PolicyName: !Sub ${ChefSubdomain}-S3Role-${AWS::Region}
         PolicyDocument: !Sub |
           {
               "Version" : "2012-10-17",
@@ -610,6 +610,8 @@ Resources:
         "Fn::Base64": !Sub |
             #!/bin/bash -xev
 
+            BUCKET="Fn::If": [ CreateChefBucket, ${ChefBucket}, ${BucketName} ]
+
             exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
 
             apt-get update && apt-get -y upgrade
@@ -649,9 +651,9 @@ Resources:
             fi
 
             # Mount S3 Bucket to Directory
-            s3fs -o allow_other -o umask=000 -o ChefRole=${ChefRole} -o endpoint=${AWS::Region} ${BUCKET} ${S3Dir} || error_exit 'Failed to mount s3fs'
+            s3fs -o allow_other -o umask=000 -o ChefRole=${ChefRole} -o endpoint=${AWS::Region} "$BUCKET" ${S3Dir} || error_exit 'Failed to mount s3fs'
 
-            echo -e "${BUCKET} ${S3Dir} fuse.s3fs rw,_netdev,allow_other,umask=000,ChefRole=${ChefRole},endpoint=${AWS::Region},retries=5,multireq_max=5 0 0" >> /etc/fstab || error_exit 'Failed to add mount info to fstab'
+            echo -e "$BUCKET ${S3Dir} fuse.s3fs rw,_netdev,allow_other,umask=000,ChefRole=${ChefRole},endpoint=${AWS::Region},retries=5,multireq_max=5 0 0" >> /etc/fstab || error_exit 'Failed to add mount info to fstab'
 
             # Sleep to allow s3fs to connect
             sleep 20
@@ -661,7 +663,7 @@ Resources:
 
             if [ ${ExistingInstall} == 'false' ]; then
                 if [ ! -f ${S3Dir}/master ]; then
-                    echo ${FQDN} > ${S3Dir}/master
+                    echo $FQDN > ${S3Dir}/master
                 fi
                 MASTER=$(cat ${S3Dir}/master)
             else
@@ -670,10 +672,6 @@ Resources:
 
             # make directories
             mkdir -p ${S3Dir}/mail ${S3Dir}/newrelic ${S3Dir}/sumologic ${S3Dir}/db ${S3Dir}/aws ${S3Dir}/certs
-
-            ## AWS Creds
-            echo "${ACCESS_KEY}" | tr -d '\n' > ${S3Dir}/aws/access_key
-            echo "${SECRET_KEY}" | tr -d '\n' > ${S3Dir}/aws/secret_key
 
             ## DB Creds
             echo "${DBUser}" | tr -d '\n' > ${S3Dir}/db/username
@@ -712,11 +710,11 @@ Resources:
             mkdir -p /etc/chef
 
             # Set hostname
-            hostname ${FQDN}  || error_exit 'Failed to set hostname'
-            echo  ${FQDN}  > /etc/hostname || error_exit 'Failed to set hostname file'
+            hostname $FQDN  || error_exit 'Failed to set hostname'
+            echo  $FQDN  > /etc/hostname || error_exit 'Failed to set hostname file'
 
             cat > '/etc/hosts' << EOF
-            127.0.0.1 ${FQDN} ${HOSTNAME} localhost
+            127.0.0.1 $FQDN $HOSTNAME localhost
             ::1 localhost6.localdomain6 localhost6
             EOF
 
@@ -724,10 +722,10 @@ Resources:
             cat > "${ChefDir}/chef_stack.json" << EOF
             {
                 "citadel": {
-                    "bucket": "${BUCKET}"
+                    "bucket": "$BUCKET"
                 },
                 "${Cookbook}": {
-                    "master": "${MASTER}",
+                    "master": "$MASTER",
                     "backup": {
                         "enable_backups": ${BackupEnable}
                     },
