Re-working some userdata items, prepping for ES Auth options, adding more error catches, adding postfix install

diff --git a/aws_backendless_chef_ha.yml b/aws_backendless_chef_ha.yml
--- a/aws_backendless_chef_ha.yml
+++ b/aws_backendless_chef_ha.yml
@@ -69,9 +69,9 @@ Parameters:
 
   ReportingVersion:
     Type: String
-    Default: "1.6.4"
+    Default: "1.6.5"
     AllowedValues:
-      - "1.6.4"
+      - "1.6.5"
     Description: Choose Version of Chef Reporting to Install (All Supported Versions listed)
 
   DisableSignup:
@@ -99,11 +99,6 @@ Parameters:
     Type: String
     Default: atat@hearst.com
     Description: Enter Support Email for Chef Server (Optional)
-
-  S3Dir:
-    Type: String
-    Default: "/opt/chef-s3"
-    Description: Path to mount S3 Bucket to (created during CFN run)
 
   ## Database Configuration
   DBUser:
@@ -230,7 +225,6 @@ Metadata:
         - SignupDisable
         - SupportEmail
         - LicenseCount
-        - S3Dir
         - BackupEnable
         - ChefServerVersion
         - ManageVersion
@@ -557,9 +551,34 @@ Resources:
 # Autoscaling
 ###############################################################################
 
+  BootstrapAutoScaleGroup:
+    Type: AWS::AutoScaling::AutoScalingGroup
+    DependsOn:
+      - ChefDB
+      - ElasticsearchDomain
+    Properties:
+      AvailabilityZones:
+        - !Select [ 0, !GetAZs "" ]
+        - !Select [ 1, !GetAZs "" ]
+        - !Select [ 2, !GetAZs "" ]
+      VPCZoneIdentifier:
+        - !Ref SubnetA
+        - !Ref SubnetB
+        - !Ref SubnetC
+      LaunchConfigurationName: !Ref ServerLaunchConfig
+      LoadBalancerNames:
+      - !Ref PrimaryElasticLoadBalancer
+      MaxSize: '1'
+      MinSize: '1'
+      Tags:
+      - Key: Name
+        Value: !Sub ${AWS::StackName}-bootstrap-frontend
+        PropagateAtLaunch: true
+
   FrontendAutoScaleGroup:
     Type: AWS::AutoScaling::AutoScalingGroup
     DependsOn:
+      - BootstrapAutoScaleGroup
       - WaitCondition
     Properties:
       AvailabilityZones:
@@ -675,13 +694,15 @@ Resources:
             - |
               #!/bin/bash -xev
 
+              # Create a separate log file specific to userdata for easier reading
               exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
 
               INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
+              BOOTSTRAP_TAGS=$(aws ec2 describe-tags --region ${AWS::Region} --filter "Name=resource-id,Values=$INSTANCE_ID" --output=text | grep BootstrapAutoScaleGroup)
               STACKNAME=${AWS::StackName}
 
               apt-get update && apt-get -y upgrade
-              apt-get install -y wget curl python-setuptools python-pip git
+              apt-get install -y wget curl python-setuptools python-pip git postfix sasl2-bin
 
               # Install cfn bootstraping tools
               if [ -z $(command -v cfn-signal) ]; then
@@ -700,66 +721,33 @@ Resources:
                 pip install awscli || error_exit "Failed to install aws cli"
               fi
 
-              # Install S3FS Dependencies
-              sudo apt-get install -y automake autotools-dev g++ git libcurl4-gnutls-dev libfuse-dev libssl-dev libxml2-dev make pkg-config
-
-              # Install S3FS
-
-              # If directory exists, remove it
-              if [ -d "/tmp/s3fs-fuse" ]; then
-                rm -rf /tmp/s3fs-fuse
+              # Install ES Proxy Auth https://github.com/lucaagostini/aws-es-auth-proxy
+              if [ -z $(command -v aws-es-auth-proxy) ]; then
+                pip install aws-es-auth-proxy || error_exit "Failed to install ES Auth Proxy"
               fi
 
-              # If s3fs command doesn't exist, install
-              if [ ! -f "/usr/local/bin/s3fs" ]; then
-                cd /tmp
-                git clone https://github.com/s3fs-fuse/s3fs-fuse.git || error_exit 'Failed to clone s3fs-fuse'
-                cd s3fs-fuse
-                ./autogen.sh || error_exit 'Failed to run autogen for s3fs-fuse'
-                ./configure || error_exit 'Failed to run configure for s3fs-fuse'
-                make || error_exit 'Failed to make s3fs-fuse'
-                sudo make install || error_exit 'Failed run make-install s3fs-fuse'
-              fi
-
-              # Create S3FS Mount Directory
-              if [ ! -d "${S3Dir}" ]; then
-                mkdir ${S3Dir}
-              fi
-
-              # Mount S3 Bucket to Directory
-              s3fs -o allow_other -o umask=000 -o iam_role=${ChefRole} -o endpoint=${AWS::Region} $BUCKET ${S3Dir} || error_exit 'Failed to mount s3fs'
-
-              echo -e "$BUCKET ${S3Dir} fuse.s3fs rw,_netdev,allow_other,umask=000,iam_role=${ChefRole},endpoint=${AWS::Region},retries=5,multireq_max=5 0 0" >> /etc/fstab || error_exit 'Failed to add mount info to fstab'
+              aws-es-auth-proxy --aws_service_endpoint ${ELASTICURL} || error_exit "Failed to initialize ES Auth Proxy"
 
               # Sleep to allow s3fs to connect
               sleep 20
 
               # Set hostname
-              hostname chef-fe-$(curl -sS http://169.254.169.254/latest/meta-data/instance-id).${HostedZone}  || error_exit 'Failed to set hostname'
-              echo  "chef-fe-$(curl -sS http://169.254.169.254/latest/meta-data/instance-id).${HostedZone}"  > /etc/hostname || error_exit 'Failed to set hostname file'
+              hostname chef-fe-${!INSTANCE_ID}.${HostedZone}  || error_exit 'Failed to set hostname'
+              echo  "chef-fe-${!INSTANCE_ID}.${HostedZone}"  > /etc/hostname || error_exit 'Failed to set hostname file'
 
               cat > '/etc/hosts' << EOF
-              127.0.0.1 $FQDN $HOSTNAME localhost
+              127.0.0.1 chef-fe-${!INSTANCE_ID}.${HostedZone} chef-fe-${!INSTANCE_ID} localhost
               ::1 localhost6.localdomain6 localhost6
               EOF
 
-              if [ ${ExistingInstall} == 'false' ]; then
-                  if [ ! -f ${S3Dir}/master ]; then
-                      echo $FQDN > ${S3Dir}/master
-                  fi
-                  MASTER=$(cat ${S3Dir}/master)
-              else
-                  MASTER=NULL
-              fi
+              CHEFSERVER=$(mktemp); wget "https://packages.chef.io/stable/ubuntu/16.04/chef-server-core_${ChefServerVersion}-1_amd64.deb" -qO $CHEFSERVER && sudo dpkg -i $CHEFSERVER; rm $CHEFSERVER  || error_exit "Failed to install Chef Server"
 
-              CHEFSERVER=`mktemp`; wget "https://packages.chef.io/stable/ubuntu/16.04/chef-server-core_${ChefServerVersion}-1_amd64.deb" -qO $CHEFSERVER && sudo dpkg -i $CHEFSERVER; rm $CHEFSERVER
+              CHEFMANAGE=$(mktemp); wget "https://packages.chef.io/stable/ubuntu/16.04/chef-manage_${ManageVersion}-1_amd64.deb" -qO $CHEFMANAGE && sudo dpkg -i $CHEFMANAGE; rm $CHEFMANAGE  || error_exit "Failed to Install Chef Manage"
 
-              CHEFMANAGE=`mktemp`; wget "https://packages.chef.io/stable/ubuntu/16.04/chef-manage_${ManageVersion}-1_amd64.deb" -qO $CHEFMANAGE && sudo dpkg -i $CHEFMANAGE; rm $CHEFMANAGE
-
-              # CHEFREPORTING=`mktemp`; wget "https://packages.chef.io/stable/ubuntu/14.04/opscode-reporting_${ReportingVersion}-1_amd64.deb" -qO $CHEFREPORTING && sudo dpkg -i $CHEFREPORTING; rm $CHEFREPORTING
+              CHEFREPORTING=$(mktemp); wget "https://packages.chef.io/stable/ubuntu/14.04/opscode-reporting_${ReportingVersion}-1_amd64.deb" -qO $CHEFREPORTING && sudo dpkg -i $CHEFREPORTING; rm $CHEFREPORTING "Failed to Install Chef Reporting"
 
               # make directories
-              mkdir -p ${S3Dir} /etc/chef-manage /etc/opscode
+              mkdir -p /etc/chef-manage /etc/opscode /etc/opscode-reporting  || error_exit "Failed to creat base Chef Directories"
 
               cat > '/etc/chef-manage/manage.rb' << EOF
               disable_sign_up ${DisableSignup}
@@ -789,7 +777,7 @@ Resources:
               opscode_erchef['search_provider'] = 'elasticsearch'
               opscode_erchef['search_queue_mode'] = 'batch'
               opscode_solr4['external'] = true
-              opscode_solr4['external_url'] = 'https://${ELASTICURL}'
+              opscode_solr4['external_url'] = 'http://127.0.0.1:8080'
               bookshelf['storage_type'] = :sql
               rabbitmq['enable'] = false
               rabbitmq['management_enabled'] = false
@@ -798,43 +786,31 @@ Resources:
               dark_launch['actions'] = false
               EOF
 
-              # If we're not master, sync down the rest of the secrets first before reconfiguring
-              if [ -f ${S3Dir}/master ]; then
-                echo "[INFO] configuring this node as a regular Chef frontend"
-                aws s3 sync s3://${!BUCKET}/${!STACKNAME}/etc_opscode /etc/opscode
-                mkdir -p /var/opt/opscode/upgrades
-                touch /var/opt/opscode/bootstrapped
-                aws s3 cp s3://${!BUCKET}/${!STACKNAME}/migration-level /var/opt/opscode/upgrades/
-              else
-                echo "[INFO] configuring this node as a Bootstrap Chef frontend"
-                echo "[INFO] initializing ElasticSearch index manually"
-                curl -XPUT https://${ElasticsearchDomain.DomainEndpoint}/chef/ -d @/tmp/index_create.json
-              fi
               if [ -z "${!BOOTSTRAP_TAGS}" ]; then
                 echo "[INFO] configuring this node as a regular Chef frontend"
-                aws s3 sync s3://${!BUCKET}/${!STACKNAME}/etc_opscode /etc/opscode
-                mkdir -p /var/opt/opscode/upgrades
-                touch /var/opt/opscode/bootstrapped
-                aws s3 cp s3://${!BUCKET}/${!STACKNAME}/migration-level /var/opt/opscode/upgrades/
-              else
-                echo "[INFO] configuring this node as a Bootstrap Chef frontend"
-                echo "[INFO] initializing ElasticSearch index manually"
-                curl -XPUT https://${ElasticsearchDomain.DomainEndpoint}/chef/ -d @/tmp/index_create.json
+                aws s3 sync s3://${!BUCKET}/etc_opscode /etc/opscode  || error_exit "Failed to sync existing Opscode Directory"
+                aws s3 sync s3://${!BUCKET}/etc_reporting /etc/opscode-reporting  || error_exit "Failed to synx existing Reporting Directory"
+                mkdir -p /var/opt/opscode/upgrades  || error_exit "Failed to create upgrades directory"
+                touch /var/opt/opscode/bootstrapped  || error_exit "Failed to create bootstrap file"
+                aws s3 cp s3://${!BUCKET}/migration-level /var/opt/opscode/upgrades/  || error_exit "Failed sync migration-level"
               fi
 
               # Configure the chef server
-              chef-server-ctl reconfigure --accept-license
-              chef-manage-ctl reconfigure --accept-license
+              chef-server-ctl reconfigure --accept-license || error_exit "Chef Server Reconfigure Failed"
+              chef-manage-ctl reconfigure --accept-license || error_exit "Chef Manage Reconfigure Failed"
 
               # The master instance should sync files after reconfigure
-              if [ ! -f ${S3Dir}/master ]; then
+              if [ -n "${!BOOTSTRAP_TAGS}" ]; then
                 echo "[INFO] syncing secrets up to S3"
-                aws s3 sync /etc/opscode s3://${!BUCKET}/${!STACKNAME}/etc_opscode
-                aws s3 cp /var/opt/opscode/upgrades/migration-level s3://${!BUCKET}/${!STACKNAME}/
+                aws s3 sync /etc/opscode s3://${!BUCKET}/etc_opscode  || error_exit "Failed to sync bootstrap opscode directory"
+                aws s3 sync /etc/opscode-reporting s3://${!BUCKET}/etc_reporting  || error_exit "Failed to sync bootstrap reporting directory"
+                aws s3 cp /var/opt/opscode/upgrades/migration-level s3://${!BUCKET}/  || error_exit "Failed to sync bootstrap migration-level"
               fi
 
+              chef-server-ctl restart || error_exit "Chef Server Restart Failed"
+
               # All is well so signal success and let CF know wait function is complete
-              /usr/local/bin/cfn-signal -e 0 -r 'Server setup complete' ${WaitHandle}
+              /usr/local/bin/cfn-signal -e 0 -r 'Server setup complete' "${WaitHandle}"
             -
               { DBENDPOINT: !GetAtt [ ChefDB, Endpoint.Address ],
                 DBPORT: !GetAtt [ ChefDB, Endpoint.Port ],
